In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('covid.csv')

In [3]:
df.head()

,Economy,code,Consumption shocks (% decline in consumption growth),Unnamed: 3,Investment shocks (% decline in investment growth),Unnamed: 5,Decline in tourism receipts (% of GDP),Unnamed: 7,Average Stringency Index,Average Mobility
0,NaN,NaN,Shorter- containment,Longer- containment,Shorter- containment,Longer- containment,Shorter- containment,Longer- containment,NaN,NaN
1,Bangladesh,BAN,7.7,11.55,12.1,18.15,-0.07,-0.11,92.5,-56.6
2,Bhutan,BTN,6.6,9.9,9.57,14.35,-2.76,-4,84.1,no data
3,Brunei Darussalam,BRN,6.42,9.64,8.97,13.46,-0.78,-1.13,57.4,no data
4,Cambodia,CAM,4.27,6.4,6.26,9.39,-11,-15.92,no data,-33.7

In [4]:
df.tail()

,Economy,code,Consumption shocks (% decline in consumption growth),Unnamed: 3,Investment shocks (% decline in investment growth),Unnamed: 5,Decline in tourism receipts (% of GDP),Unnamed: 7,Average Stringency Index,Average Mobility
20,Singapore,SIN,7.3,10.95,7.7,11.55,-3.13,-4.53,55.6,-25.9
21,Sri Lanka,SRI,7.33,10.99,11.78,17.67,-3.52,-5.1,90.5,-66.4
22,"Taipei,China",TAP,2,3,2.7,4.05,-2.41,-3.48,29.7,-6.9
23,Thailand,THA,6.6,9.9,8.9,13.35,-7.22,-10.45,71.2,-33.7
24,Viet Nam,VIE,3.57,5.35,5.13,7.7,-2.3,-3.32,75.5,-31.2

In [5]:
df.tail(2)

,Economy,code,Consumption shocks (% decline in consumption growth),Unnamed: 3,Investment shocks (% decline in investment growth),Unnamed: 5,Decline in tourism receipts (% of GDP),Unnamed: 7,Average Stringency Index,Average Mobility
23,Thailand,THA,6.6,9.9,8.9,13.35,-7.22,-10.45,71.2,-33.7
24,Viet Nam,VIE,3.57,5.35,5.13,7.7,-2.3,-3.32,75.5,-31.2

In [6]:
df.dtypes

Economy                                                 object
code                                                    object
Consumption shocks (% decline in consumption growth)    object
Unnamed: 3                                              object
Investment shocks (% decline in investment growth)      object
Unnamed: 5                                              object
Decline in tourism receipts (% of GDP)                  object
Unnamed: 7                                              object
Average Stringency Index                                object
Average Mobility                                        object
dtype: object

In [11]:
df['Average Mobility']

0         NaN
1       -56.6
2     no data
3     no data
4       -33.7
5       -33.4
6       -18.8
7       -52.9
8       -32.5
9       -40.8
10      -59.3
11        -42
12      -51.8
13    no data
14       -0.5
15        -62
16      -44.6
17    no data
18      -63.2
19       -4.2
20      -25.9
21      -66.4
22       -6.9
23      -33.7
24      -31.2
Name: Average Mobility, dtype: object

In [12]:
df['Consumption shocks (% decline in consumption growth)']

0     Shorter- containment
1                      7.7
2                      6.6
3                     6.42
4                     4.27
5                     4.97
6                      5.2
7                      6.4
8                        5
9                     7.46
10                    7.99
11                    3.67
12                     6.7
13                    7.31
14                    3.78
15                    6.28
16                    7.26
17                    5.46
18                     6.2
19                     4.8
20                     7.3
21                    7.33
22                       2
23                     6.6
24                    3.57
Name: Consumption shocks (% decline in consumption growth), dtype: object

In [14]:
type(df['Unnamed: 3'])

pandas.core.series.Series

In [15]:
df.sum()

Series([], dtype: float64)

In [16]:
df.isnull().sum()

Economy                                                 1
code                                                    1
Consumption shocks (% decline in consumption growth)    0
Unnamed: 3                                              0
Investment shocks (% decline in investment growth)      0
Unnamed: 5                                              0
Decline in tourism receipts (% of GDP)                  0
Unnamed: 7                                              0
Average Stringency Index                                1
Average Mobility                                        1
dtype: int64

In [17]:
df.isnull()

,Economy,code,Consumption shocks (% decline in consumption growth),Unnamed: 3,Investment shocks (% decline in investment growth),Unnamed: 5,Decline in tourism receipts (% of GDP),Unnamed: 7,Average Stringency Index,Average Mobility
0,True,True,False,False,False,False,False,False,True,True
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False

In [36]:
df['Institute']="scooden"

In [44]:
df

,Economy,code,Consumption shocks (% decline in consumption growth),Unnamed: 3,Investment shocks (% decline in investment growth),Unnamed: 5,Decline in tourism receipts (% of GDP),Unnamed: 7,Average Stringency Index,Average Mobility,Institute
0,NaN,NaN,Shorter- containment,Longer- containment,Shorter- containment,Longer- containment,Shorter- containment,Longer- containment,NaN,NaN,scooden
1,Bangladesh,BAN,7.7,11.55,12.1,18.15,-0.07,-0.11,92.5,-56.6,scooden
2,Bhutan,BTN,6.6,9.9,9.57,14.35,-2.76,-4,84.1,no data,scooden
3,Brunei Darussalam,BRN,6.42,9.64,8.97,13.46,-0.78,-1.13,57.4,no data,scooden
4,Cambodia,CAM,4.27,6.4,6.26,9.39,-11,-15.92,no data,-33.7,scooden
5,Fiji,FIJ,4.97,7.46,7.33,11,-13.83,-20.01,no data,-33.4,scooden
6,"Hong Kong, China",HKG,5.2,7.8,9.9,14.85,-6.38,-9.23,60.6,-18.8,scooden
7,India,IND,6.4,9.6,10.9,16.35,-0.6,-0.87,86.8,-52.9,scooden
8,Indonesia,IDN,5,7.5,6.5,9.75,-0.84,-1.21,61.4,-32.5,scooden
9,Kazakhstan,KAZ,7.46,11.2,11.33,17,-0.83,-1.2,82.8,-40.8,scooden
10,Kyrgyz Republic,KGZ,7.99,11.98,12.61,18.91,-3.36,-4.87,85.4,-59.3,scooden
11,Lao People's Democratic Republic,LAO,3.67,5.5,5.42,8.13,-2.36,-3.41,90.6,-42,scooden
12,Malaysia,MAL,6.7,10.05,8.6,12.9,-3.39,-4.91,64.9,-51.8,scooden
13,Maldives,MDV,7.31,10.96,11.06,16.6,-32.03,-46.36,no data,no data,scooden
14,Mongolia,MON,3.78,5.67,4.67,7.01,-2.25,-3.25,68,-0.5,scooden
15,Nepal,NPL,6.28,9.41,10.06,15.09,-1.43,-2.07,95.2,-62,scooden
16,Pakistan,PAK,7.26,10.89,11.11,16.67,-0.15,-0.21,90.1,-44.6,scooden
17,People's Republic of China,CHN,5.46,8.19,7.14,10.72,-0.14,-0.2,57.5,no data,scooden
18,Philippines,PHI,6.2,9.3,13.3,19.95,-1.64,-2.37,92.9,-63.2,scooden
19,Republic of Korea,KOR,4.8,7.2,2.3,3.45,-0.68,-0.99,63.1,-4.2,scooden
20,Singapore,SIN,7.3,10.95,7.7,11.55,-3.13,-4.53,55.6,-25.9,scooden
21,Sri Lanka,SRI,7.33,10.99,11.78,17.67,-3.52,-5.1,90.5,-66.4,scooden
22,"Taipei,China",TAP,2,3,2.7,4.05,-2.41,-3.48,29.7,-6.9,scooden
23,Thailand,THA,6.6,9.9,8.9,13.35,-7.22,-10.45,71.2,-33.7,scooden
24,Viet Nam,VIE,3.57,5.35,5.13,7.7,-2.3,-3.32,75.5,-31.2,scooden

In [45]:
df.drop(columns='Institute',axis=1,inplace=True)

In [49]:
df

,Economy,code,Consumption shocks (% decline in consumption growth),Unnamed: 3,Investment shocks (% decline in investment growth),Unnamed: 5,Decline in tourism receipts (% of GDP),Unnamed: 7,Average Stringency Index
0,NaN,NaN,Shorter- containment,Longer- containment,Shorter- containment,Longer- containment,Shorter- containment,Longer- containment,NaN
1,Bangladesh,BAN,7.7,11.55,12.1,18.15,-0.07,-0.11,92.5
2,Bhutan,BTN,6.6,9.9,9.57,14.35,-2.76,-4,84.1
3,Brunei Darussalam,BRN,6.42,9.64,8.97,13.46,-0.78,-1.13,57.4
4,Cambodia,CAM,4.27,6.4,6.26,9.39,-11,-15.92,no data
5,Fiji,FIJ,4.97,7.46,7.33,11,-13.83,-20.01,no data
6,"Hong Kong, China",HKG,5.2,7.8,9.9,14.85,-6.38,-9.23,60.6
7,India,IND,6.4,9.6,10.9,16.35,-0.6,-0.87,86.8
8,Indonesia,IDN,5,7.5,6.5,9.75,-0.84,-1.21,61.4
9,Kazakhstan,KAZ,7.46,11.2,11.33,17,-0.83,-1.2,82.8
10,Kyrgyz Republic,KGZ,7.99,11.98,12.61,18.91,-3.36,-4.87,85.4
11,Lao People's Democratic Republic,LAO,3.67,5.5,5.42,8.13,-2.36,-3.41,90.6
12,Malaysia,MAL,6.7,10.05,8.6,12.9,-3.39,-4.91,64.9
13,Maldives,MDV,7.31,10.96,11.06,16.6,-32.03,-46.36,no data
14,Mongolia,MON,3.78,5.67,4.67,7.01,-2.25,-3.25,68
15,Nepal,NPL,6.28,9.41,10.06,15.09,-1.43,-2.07,95.2
16,Pakistan,PAK,7.26,10.89,11.11,16.67,-0.15,-0.21,90.1
17,People's Republic of China,CHN,5.46,8.19,7.14,10.72,-0.14,-0.2,57.5
18,Philippines,PHI,6.2,9.3,13.3,19.95,-1.64,-2.37,92.9
19,Republic of Korea,KOR,4.8,7.2,2.3,3.45,-0.68,-0.99,63.1
20,Singapore,SIN,7.3,10.95,7.7,11.55,-3.13,-4.53,55.6
21,Sri Lanka,SRI,7.33,10.99,11.78,17.67,-3.52,-5.1,90.5
22,"Taipei,China",TAP,2,3,2.7,4.05,-2.41,-3.48,29.7
23,Thailand,THA,6.6,9.9,8.9,13.35,-7.22,-10.45,71.2
24,Viet Nam,VIE,3.57,5.35,5.13,7.7,-2.3,-3.32,75.5

In [50]:
dfnew=df.drop(columns="Average Stringency Index",axis=1)

In [51]:
df

,Economy,code,Consumption shocks (% decline in consumption growth),Unnamed: 3,Investment shocks (% decline in investment growth),Unnamed: 5,Decline in tourism receipts (% of GDP),Unnamed: 7,Average Stringency Index
0,NaN,NaN,Shorter- containment,Longer- containment,Shorter- containment,Longer- containment,Shorter- containment,Longer- containment,NaN
1,Bangladesh,BAN,7.7,11.55,12.1,18.15,-0.07,-0.11,92.5
2,Bhutan,BTN,6.6,9.9,9.57,14.35,-2.76,-4,84.1
3,Brunei Darussalam,BRN,6.42,9.64,8.97,13.46,-0.78,-1.13,57.4
4,Cambodia,CAM,4.27,6.4,6.26,9.39,-11,-15.92,no data
5,Fiji,FIJ,4.97,7.46,7.33,11,-13.83,-20.01,no data
6,"Hong Kong, China",HKG,5.2,7.8,9.9,14.85,-6.38,-9.23,60.6
7,India,IND,6.4,9.6,10.9,16.35,-0.6,-0.87,86.8
8,Indonesia,IDN,5,7.5,6.5,9.75,-0.84,-1.21,61.4
9,Kazakhstan,KAZ,7.46,11.2,11.33,17,-0.83,-1.2,82.8
10,Kyrgyz Republic,KGZ,7.99,11.98,12.61,18.91,-3.36,-4.87,85.4
11,Lao People's Democratic Republic,LAO,3.67,5.5,5.42,8.13,-2.36,-3.41,90.6
12,Malaysia,MAL,6.7,10.05,8.6,12.9,-3.39,-4.91,64.9
13,Maldives,MDV,7.31,10.96,11.06,16.6,-32.03,-46.36,no data
14,Mongolia,MON,3.78,5.67,4.67,7.01,-2.25,-3.25,68
15,Nepal,NPL,6.28,9.41,10.06,15.09,-1.43,-2.07,95.2
16,Pakistan,PAK,7.26,10.89,11.11,16.67,-0.15,-0.21,90.1
17,People's Republic of China,CHN,5.46,8.19,7.14,10.72,-0.14,-0.2,57.5
18,Philippines,PHI,6.2,9.3,13.3,19.95,-1.64,-2.37,92.9
19,Republic of Korea,KOR,4.8,7.2,2.3,3.45,-0.68,-0.99,63.1
20,Singapore,SIN,7.3,10.95,7.7,11.55,-3.13,-4.53,55.6
21,Sri Lanka,SRI,7.33,10.99,11.78,17.67,-3.52,-5.1,90.5
22,"Taipei,China",TAP,2,3,2.7,4.05,-2.41,-3.48,29.7
23,Thailand,THA,6.6,9.9,8.9,13.35,-7.22,-10.45,71.2
24,Viet Nam,VIE,3.57,5.35,5.13,7.7,-2.3,-3.32,75.5

In [52]:
dfnew

,Economy,code,Consumption shocks (% decline in consumption growth),Unnamed: 3,Investment shocks (% decline in investment growth),Unnamed: 5,Decline in tourism receipts (% of GDP),Unnamed: 7
0,NaN,NaN,Shorter- containment,Longer- containment,Shorter- containment,Longer- containment,Shorter- containment,Longer- containment
1,Bangladesh,BAN,7.7,11.55,12.1,18.15,-0.07,-0.11
2,Bhutan,BTN,6.6,9.9,9.57,14.35,-2.76,-4
3,Brunei Darussalam,BRN,6.42,9.64,8.97,13.46,-0.78,-1.13
4,Cambodia,CAM,4.27,6.4,6.26,9.39,-11,-15.92
5,Fiji,FIJ,4.97,7.46,7.33,11,-13.83,-20.01
6,"Hong Kong, China",HKG,5.2,7.8,9.9,14.85,-6.38,-9.23
7,India,IND,6.4,9.6,10.9,16.35,-0.6,-0.87
8,Indonesia,IDN,5,7.5,6.5,9.75,-0.84,-1.21
9,Kazakhstan,KAZ,7.46,11.2,11.33,17,-0.83,-1.2
10,Kyrgyz Republic,KGZ,7.99,11.98,12.61,18.91,-3.36,-4.87
11,Lao People's Democratic Republic,LAO,3.67,5.5,5.42,8.13,-2.36,-3.41
12,Malaysia,MAL,6.7,10.05,8.6,12.9,-3.39,-4.91
13,Maldives,MDV,7.31,10.96,11.06,16.6,-32.03,-46.36
14,Mongolia,MON,3.78,5.67,4.67,7.01,-2.25,-3.25
15,Nepal,NPL,6.28,9.41,10.06,15.09,-1.43,-2.07
16,Pakistan,PAK,7.26,10.89,11.11,16.67,-0.15,-0.21
17,People's Republic of China,CHN,5.46,8.19,7.14,10.72,-0.14,-0.2
18,Philippines,PHI,6.2,9.3,13.3,19.95,-1.64,-2.37
19,Republic of Korea,KOR,4.8,7.2,2.3,3.45,-0.68,-0.99
20,Singapore,SIN,7.3,10.95,7.7,11.55,-3.13,-4.53
21,Sri Lanka,SRI,7.33,10.99,11.78,17.67,-3.52,-5.1
22,"Taipei,China",TAP,2,3,2.7,4.05,-2.41,-3.48
23,Thailand,THA,6.6,9.9,8.9,13.35,-7.22,-10.45
24,Viet Nam,VIE,3.57,5.35,5.13,7.7,-2.3,-3.32

In [53]:
df123=df.copy()

In [54]:
df123

,Economy,code,Consumption shocks (% decline in consumption growth),Unnamed: 3,Investment shocks (% decline in investment growth),Unnamed: 5,Decline in tourism receipts (% of GDP),Unnamed: 7,Average Stringency Index
0,NaN,NaN,Shorter- containment,Longer- containment,Shorter- containment,Longer- containment,Shorter- containment,Longer- containment,NaN
1,Bangladesh,BAN,7.7,11.55,12.1,18.15,-0.07,-0.11,92.5
2,Bhutan,BTN,6.6,9.9,9.57,14.35,-2.76,-4,84.1
3,Brunei Darussalam,BRN,6.42,9.64,8.97,13.46,-0.78,-1.13,57.4
4,Cambodia,CAM,4.27,6.4,6.26,9.39,-11,-15.92,no data
5,Fiji,FIJ,4.97,7.46,7.33,11,-13.83,-20.01,no data
6,"Hong Kong, China",HKG,5.2,7.8,9.9,14.85,-6.38,-9.23,60.6
7,India,IND,6.4,9.6,10.9,16.35,-0.6,-0.87,86.8
8,Indonesia,IDN,5,7.5,6.5,9.75,-0.84,-1.21,61.4
9,Kazakhstan,KAZ,7.46,11.2,11.33,17,-0.83,-1.2,82.8
10,Kyrgyz Republic,KGZ,7.99,11.98,12.61,18.91,-3.36,-4.87,85.4
11,Lao People's Democratic Republic,LAO,3.67,5.5,5.42,8.13,-2.36,-3.41,90.6
12,Malaysia,MAL,6.7,10.05,8.6,12.9,-3.39,-4.91,64.9
13,Maldives,MDV,7.31,10.96,11.06,16.6,-32.03,-46.36,no data
14,Mongolia,MON,3.78,5.67,4.67,7.01,-2.25,-3.25,68
15,Nepal,NPL,6.28,9.41,10.06,15.09,-1.43,-2.07,95.2
16,Pakistan,PAK,7.26,10.89,11.11,16.67,-0.15,-0.21,90.1
17,People's Republic of China,CHN,5.46,8.19,7.14,10.72,-0.14,-0.2,57.5
18,Philippines,PHI,6.2,9.3,13.3,19.95,-1.64,-2.37,92.9
19,Republic of Korea,KOR,4.8,7.2,2.3,3.45,-0.68,-0.99,63.1
20,Singapore,SIN,7.3,10.95,7.7,11.55,-3.13,-4.53,55.6
21,Sri Lanka,SRI,7.33,10.99,11.78,17.67,-3.52,-5.1,90.5
22,"Taipei,China",TAP,2,3,2.7,4.05,-2.41,-3.48,29.7
23,Thailand,THA,6.6,9.9,8.9,13.35,-7.22,-10.45,71.2
24,Viet Nam,VIE,3.57,5.35,5.13,7.7,-2.3,-3.32,75.5

In [55]:
df.dropna()

,Economy,code,Consumption shocks (% decline in consumption growth),Unnamed: 3,Investment shocks (% decline in investment growth),Unnamed: 5,Decline in tourism receipts (% of GDP),Unnamed: 7,Average Stringency Index
1,Bangladesh,BAN,7.7,11.55,12.1,18.15,-0.07,-0.11,92.5
2,Bhutan,BTN,6.6,9.9,9.57,14.35,-2.76,-4,84.1
3,Brunei Darussalam,BRN,6.42,9.64,8.97,13.46,-0.78,-1.13,57.4
4,Cambodia,CAM,4.27,6.4,6.26,9.39,-11,-15.92,no data
5,Fiji,FIJ,4.97,7.46,7.33,11,-13.83,-20.01,no data
6,"Hong Kong, China",HKG,5.2,7.8,9.9,14.85,-6.38,-9.23,60.6
7,India,IND,6.4,9.6,10.9,16.35,-0.6,-0.87,86.8
8,Indonesia,IDN,5,7.5,6.5,9.75,-0.84,-1.21,61.4
9,Kazakhstan,KAZ,7.46,11.2,11.33,17,-0.83,-1.2,82.8
10,Kyrgyz Republic,KGZ,7.99,11.98,12.61,18.91,-3.36,-4.87,85.4
11,Lao People's Democratic Republic,LAO,3.67,5.5,5.42,8.13,-2.36,-3.41,90.6
12,Malaysia,MAL,6.7,10.05,8.6,12.9,-3.39,-4.91,64.9
13,Maldives,MDV,7.31,10.96,11.06,16.6,-32.03,-46.36,no data
14,Mongolia,MON,3.78,5.67,4.67,7.01,-2.25,-3.25,68
15,Nepal,NPL,6.28,9.41,10.06,15.09,-1.43,-2.07,95.2
16,Pakistan,PAK,7.26,10.89,11.11,16.67,-0.15,-0.21,90.1
17,People's Republic of China,CHN,5.46,8.19,7.14,10.72,-0.14,-0.2,57.5
18,Philippines,PHI,6.2,9.3,13.3,19.95,-1.64,-2.37,92.9
19,Republic of Korea,KOR,4.8,7.2,2.3,3.45,-0.68,-0.99,63.1
20,Singapore,SIN,7.3,10.95,7.7,11.55,-3.13,-4.53,55.6
21,Sri Lanka,SRI,7.33,10.99,11.78,17.67,-3.52,-5.1,90.5
22,"Taipei,China",TAP,2,3,2.7,4.05,-2.41,-3.48,29.7
23,Thailand,THA,6.6,9.9,8.9,13.35,-7.22,-10.45,71.2
24,Viet Nam,VIE,3.57,5.35,5.13,7.7,-2.3,-3.32,75.5

In [26]:
import pandas as pd

In [27]:
df=pd.read_csv('C:/Users/Admin/Desktop/data.csv')

In [28]:
df.head(20)

    Unnamed: 0         A         B         C         D
0            0 -1.557181  0.373416  1.040685 -0.648513
1            1 -0.835872 -0.005259  0.502099 -0.956839
2            2 -0.257153  2.638228 -0.535731 -1.069443
3            3 -0.505502 -0.339260  0.602622 -1.420995
4            4  1.366398 -0.368296  0.642091  1.609680
5            5 -1.350101  0.210097 -0.743280  0.035729
6            6 -0.621305 -0.620733  0.141429 -1.831875
7            7 -0.670370 -0.379230  1.950228 -0.487202
8            8 -1.360577  0.044675 -0.576289  0.998686
9            9 -0.120302 -0.146491 -0.420956  1.412786
10          10  0.216936  0.398267  0.342519  0.387263
11          11  0.567832 -2.023668 -0.315318 -0.064349
12          12 -0.161148 -0.118924 -1.226679 -0.932540
13          13 -1.063620  0.041304 -1.037695  0.628520
14          14  0.912931  0.848745 -1.215276 -0.024202
15          15 -0.661489 -1.543994 -0.452754 -1.589521
16          16 -0.272063 -1.012084  0.414147 -0.021171
17          17  0.468146  0.232378 -1.890289  0.827622
18          18  1.744694  0.052282  0.890462 -0.155540
19          19  0.381029  0.666666  0.957832  1.476093

In [29]:
df.describe()

       Unnamed: 0          A          B          C          D
count    50.00000  50.000000  50.000000  50.000000  50.000000
mean     24.50000   0.020103  -0.123273  -0.044716   0.059140
std      14.57738   1.139660   0.845836   0.848863   0.966854
min       0.00000  -2.085251  -2.023668  -1.890289  -1.831875
25%      12.25000  -0.677750  -0.608653  -0.582724  -0.622080
50%      24.50000  -0.090116   0.000591  -0.215810  -0.091596
75%      36.75000   0.578342   0.361622   0.493181   0.813681
max      49.00000   2.762885   2.638228   1.950228   1.983037

In [30]:
df.shape

(50, 5)

In [31]:
df.columns

Index(['Unnamed: 0', 'A', 'B', 'C', 'D'], dtype='object')

In [35]:
df.rename({"A":"First","B":"Second"},axis=1,inplace=True)

In [36]:
df

    Unnamed: 0     First    Second         C         D
0            0 -1.557181  0.373416  1.040685 -0.648513
1            1 -0.835872 -0.005259  0.502099 -0.956839
2            2 -0.257153  2.638228 -0.535731 -1.069443
3            3 -0.505502 -0.339260  0.602622 -1.420995
4            4  1.366398 -0.368296  0.642091  1.609680
5            5 -1.350101  0.210097 -0.743280  0.035729
6            6 -0.621305 -0.620733  0.141429 -1.831875
7            7 -0.670370 -0.379230  1.950228 -0.487202
8            8 -1.360577  0.044675 -0.576289  0.998686
9            9 -0.120302 -0.146491 -0.420956  1.412786
10          10  0.216936  0.398267  0.342519  0.387263
11          11  0.567832 -2.023668 -0.315318 -0.064349
12          12 -0.161148 -0.118924 -1.226679 -0.932540
13          13 -1.063620  0.041304 -1.037695  0.628520
14          14  0.912931  0.848745 -1.215276 -0.024202
15          15 -0.661489 -1.543994 -0.452754 -1.589521
16          16 -0.272063 -1.012084  0.414147 -0.021171
17          17  0.468146  0.232378 -1.890289  0.827622
18          18  1.744694  0.052282  0.890462 -0.155540
19          19  0.381029  0.666666  0.957832  1.476093
20          20  0.503970  0.567258  1.578919  1.041839
21          21 -0.561937  0.534243  0.246232  0.763021
22          22  0.064446 -0.483406 -0.584869 -1.066767
23          23  2.762885  0.060047 -0.709070 -1.350154
24          24 -0.399912  0.755714 -0.138098  0.771859
25          25  2.289132 -0.178023  0.392030 -1.638884
26          26 -1.667799 -0.723245 -0.298492 -0.464406
27          27  0.871473 -0.875910  1.693428 -0.120278
28          28  2.035892 -0.442804  1.710999 -0.164896
29          29  2.646331  0.006441 -0.819143 -0.140657
30          30 -1.645022  1.841754 -0.390258 -0.118842
31          31 -2.085251  0.043444 -0.183578  0.548298
32          32  1.427635 -0.349981  1.038814 -0.955178
33          33 -0.680210  0.566180 -0.325638  0.244383
34          34 -0.026502  0.758021  0.466427 -0.198146
35          35  0.433309  0.623019 -0.201789  1.983037
36          36  0.646673 -0.715421 -0.322057  0.645001
37          37  0.048681 -1.203145  0.460026  0.192644
38          38  0.098718 -0.672915 -0.229832 -0.187133
39          39 -0.059930 -1.472300 -1.281250 -0.666214
40          40  1.515724  0.207993 -1.037067 -0.393363
41          41 -0.949868 -1.115604 -0.554789  1.324991
42          42 -1.452316 -0.572414 -0.808790  1.615190
43          43 -1.117542  0.083952 -0.874761  0.884389
44          44  0.834118  0.423509 -0.565575 -0.169843
45          45 -0.382312  0.175994 -0.820539 -0.542783
46          46 -0.982393 -0.396464  0.550612  1.584936
47          47  0.581846 -0.994098  0.519327  1.286765
48          48 -0.412282 -1.889874 -0.047348 -0.767669
49          49  0.446292  0.326242  0.230500  0.841655

In [39]:
df['First'].describe()

count    50.000000
mean      0.020103
std       1.139660
min      -2.085251
25%      -0.677750
50%      -0.090116
75%       0.578342
max       2.762885
Name: First, dtype: float64

In [40]:
df.describe(include=['float64','object'])

           First     Second          C          D
count  50.000000  50.000000  50.000000  50.000000
mean    0.020103  -0.123273  -0.044716   0.059140
std     1.139660   0.845836   0.848863   0.966854
min    -2.085251  -2.023668  -1.890289  -1.831875
25%    -0.677750  -0.608653  -0.582724  -0.622080
50%    -0.090116   0.000591  -0.215810  -0.091596
75%     0.578342   0.361622   0.493181   0.813681
max     2.762885   2.638228   1.950228   1.983037